services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: blog-config-server
    ports:
      - "${CONFIG_SERVER_PORT:-8888}:8888"
    networks:
      - blog-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "http://localhost:8888/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT:-8888}
      - CONFIG_SERVER_USERNAME=${CONFIG_SERVER_USERNAME}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PASSWORD}
      - CONFIG_REPO_URI=${CONFIG_REPO_URI}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
      - CONFIG_DEFAULT_LABEL=${CONFIG_DEFAULT_LABEL}
      - CONFIG_SEARCH_PATHS=${CONFIG_SEARCH_PATHS}
    env_file:
      - ./config-server/.env

  mongodb:
    image: mongo:latest
    container_name: blog-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - blog-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASS}
      - MONGO_INITDB_DATABASE=admin
    command: ["mongod", "--auth"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  blog-backend:
    build:
      context: ./blog-backend
      dockerfile: Dockerfile
    container_name: blog-backend-service
    ports:
      - "${BLOG_BACKEND_SERVER_PORT:-8080}:8080"
    networks:
      - blog-network
    depends_on:
      config-server:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - BLOG_BACKEND_SERVER_PORT=${BLOG_BACKEND_SERVER_PORT:-8080}
      - CONFIG_SERVER_USERNAME=${CONFIG_SERVER_USERNAME}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PASSWORD}
      - MONGODB_DEV_URI=${MONGODB_DEV_URI}
    env_file:
      - ./blog-backend/.env
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "http://localhost:8080/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  blog-network:
    name: blog-network
    driver: bridge

volumes:
  mongodb_data:
    name: blog-mongodb-data
